updating wzup and nvup functions

diff --git a/functions/nvup b/functions/nvup
--- a/functions/nvup
+++ b/functions/nvup
@@ -1,31 +1,31 @@
 #!/bin/zsh
 
-set -e
-
 force=false
 [[ "$1" == "--force" || "$1" == "-f" ]] && force=true
 
-pushd $(pwd)
+local start_dir=$PWD
+{
 
 if [[ $(uname) == "Darwin" ]]; then
   if ! command -v brew &>/dev/null; then
     echo "brew is not installed"
-    exit 1
+    return 1
   elif ! command -v nvim &>/dev/null; then
     echo "neovim is not installed!"
     #echo "installing neovim..."
     #brew install --cask wezterm@nightly
-    exit 1
+    return 1
   else
     # brew upgrade neovim --HEAD
     if [[ -d ${XDG_PROJECTS_DIR}/neovim ]]; then
-      pushd ${XDG_PROJECTS_DIR}/neovim
-      git fetch
+      {
+      cd -- "${XDG_PROJECTS_DIR}/neovim" || { echo "failed to cd into neovim project dir"; return 1; }
+      git fetch || { echo "git fetch failed"; return 1; }
       local has_changes=$(git rev-list HEAD...origin/master --count)
       if [[ $force == true ]] || [[ $has_changes != 0 ]]; then
         [[ $force == true ]] && echo "Forcing rebuild..."
         if [[ -d build ]]; then
-          git reset --hard && git clean --force -dfx && git pull
+          git reset --hard && git clean --force -dfx && git pull || { echo "git reset/clean/pull failed"; return 1; }
         fi
         if command -v make &>/dev/null; then
           local nprocs=$(($(sysctl -n hw.logicalcpu) - 1))
@@ -33,14 +33,16 @@ if [[ $(uname) == "Darwin" ]]; then
             CC=clang CXX=clang++ \
             CFLAGS="-O3 -mcpu=apple-m4 -ffast-math -flto=full -fstack-protector-strong -fno-plt" \
             LDFLAGS="-flto=full" \
-            -j$nprocs
-          make install
+            -j$nprocs || { echo "make failed"; return 1; }
+          make install || { echo "make install failed"; return 1; }
         else
           echo "make is not installed"
-          exit 1
+          return 1
         fi
       fi
-      popd
+      } always {
+        cd -- "$start_dir"
+      }
     fi
   fi
 elif [[ $(lsb_release -is) == "Arch" && $(whoami) == "dakota" ]]; then
@@ -48,29 +50,33 @@ elif [[ $(lsb_release -is) == "Arch" && $(whoami) == "dakota" ]]; then
     echo "neovim is not installed!"
   else
     if [[ -d ${XDG_PROJECTS_DIR}/neovim ]]; then
-      pushd ${XDG_PROJECTS_DIR}/neovim
-      git fetch
+      {
+      cd -- "${XDG_PROJECTS_DIR}/neovim" || { echo "failed to cd into neovim project dir"; return 1; }
+      git fetch || { echo "git fetch failed"; return 1; }
       local has_changes=$(git rev-list HEAD...origin/master --count)
       if [[ $force == true ]] || [[ $has_changes != 0 ]]; then
         [[ $force == true ]] && echo "Forcing rebuild..."
         if [[ -d build ]]; then
-          git reset --hard && git clean --force -dfx && git pull
+          git reset --hard && git clean --force -dfx && git pull || { echo "git reset/clean/pull failed"; return 1; }
         fi
         if command -v make &>/dev/null; then
           make CC=clang CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$HOME/.local CFLAGS="-march=znver5 \
             -mtune=znver5 -Ofast -lm -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
-            -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
-          make install
+            -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer" || { echo "make failed"; return 1; }
+          make install || { echo "make install failed"; return 1; }
         else
           echo "make is not installed"
-          exit 1
+          return 1
         fi
       fi
-      popd
+      } always {
+        cd -- "$start_dir"
+      }
     fi
   fi
 fi
-
-popd
+} always {
+  cd -- "$start_dir"
+}
 
 # vim: set ft=sh ts=2 sw=2 et:
